version = "Two"
edition = "2024"
binop_separator = "Back"
condense_wildcard_suffixes = true
brace_style = "PreferSameLine"
where_single_line = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
normalize_comments = true
reorder_impl_items = true
trailing_comma = "Never"
trailing_semicolon = false
use_field_init_shorthand = true
use_try_shorthand = true
overflow_delimited_expr = true
max_width = 80
