[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "BSD-2-Clause"
authors = ["Guillaume 'Yugo' Coguiec <mail@gcoguiec.com>"]

[workspace.dependencies]
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
