cargo-features = ["edition2024"]

[[bin]]
name = "pfconf-ls"
path = "src/bin/main.rs"

[package]
name = "pfconf-ls"
version = "0.1.0"
edition = "2024"

[dependencies]
cfg-if = "1.0.0"
libc = "0.2.153"
lsp-server = "0.7.6"
lsp-types = "0.95.1"
miette = { version = "7.2.0", features = ["fancy"] }
thiserror = "1.0.58"
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", default-features = false, features = ["fmt", "env-filter", "ansi"] }
xflags = "0.3.2"
pfconf-tree-sitter = { path = "../pfconf-tree-sitter" }

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
version = "0.52.0"
features = [
    "Win32_System_Threading"
]
